import { stringify } from "yaml";
import type { ConfigExporter } from "../types";
import { toMihomoProxy } from "./proxy-options";

export function rejectClientGeneral(raw: string, errors: string[]) {
  if (raw.split(/\r?\n/).some(line => line.trim() && !line.trim().startsWith("#"))) errors.push("高级通用参数是 Shadowrocket 专用语法；请清空这些参数后再导出此客户端");
  return [];
}
export const clashExporter: ConfigExporter = {
  id: "clash", name: "Clash / Mihomo", extension: ".yaml",
  parseGeneral: rejectClientGeneral,
  serialize(model) {
    const proxies = (model.sources ?? []).map(({ node, alias }) => toMihomoProxy(node, alias));
    const rules = model.rules.map(rule => {
      const target = rule.target ?? rule.policy;
      if (target === "PROXY") throw new Error("请先在默认代理或对应应用/规则中选择节点，再导出 Clash / Mihomo 配置");
      return rule.type === "FINAL" ? `MATCH,${target}` : `${rule.type},${rule.value},${target}${rule.noResolve ? ",no-resolve" : ""}`;
    });
    return "# Generated by RouteKit — contains proxy credentials.\n# Import into a Mihomo-compatible client; rules use its GeoIP database.\n" + stringify({
      "mixed-port": 7890, "allow-lan": false, "bind-address": "127.0.0.1",
      mode: "rule", "log-level": "warning", ipv6: model.ipv6,
      dns: { enable: true, ipv6: model.ipv6, "enhanced-mode": "redir-host", "use-hosts": true,
        "use-system-hosts": false, "default-nameserver": ["223.5.5.5", "1.1.1.1"],
        nameserver: model.servers.map(server => server === "system" ? "system" : server),
      },
      hosts: Object.fromEntries(model.hosts.map(item => [item.hostname, item.address])),
      proxies, rules,
    }, { lineWidth: 0 });
  },
};
