import type { ConfigExporter, GeneralOption } from "../types";

const ADVANCED_BOOLEAN = new Set([
  "icmp-auto-reply",
  "always-reject-url-rewrite",
  "private-ip-answer",
  "use-local-host-item-for-proxy",
  "close-if-proxy-chain-missing",
]);
const RESERVED_GENERAL = new Set([
  "bypass-system",
  "dns-server",
  "fallback-dns-server",
  "ipv6",
  "prefer-ipv6",
  "dns-direct-system",
  "dns-direct-fallback-proxy",
  "udp-policy-not-supported-behaviour",
]);

export const shadowrocketExporter: ConfigExporter = {
  id: "shadowrocket",
  name: "Shadowrocket",
  extension: ".conf",
  parseGeneral(raw, errors) {
    const options: GeneralOption[] = [],
      seen = new Set<string>();
    for (const [index, entry] of raw.split(/\r?\n/).entries()) {
      const line = entry.trim();
      if (!line || line.startsWith("#")) continue;
      const match = /^([a-z][a-z-]+)\s*=\s*(true|false)$/.exec(line);
      if (!match) {
        errors.push(
          `通用参数第 ${index + 1} 行格式不受支持；请使用允许的 key = true/false`,
        );
        continue;
      }
      const [, key, value] = match;
      if (RESERVED_GENERAL.has(key)) {
        errors.push(`${key} 由上方表单生成，请在对应设置中修改`);
        continue;
      }
      if (!ADVANCED_BOOLEAN.has(key)) {
        errors.push(`暂不支持通用参数 ${key}`);
        continue;
      }
      if (seen.has(key)) {
        errors.push(`通用参数 ${key} 重复`);
        continue;
      }
      seen.add(key);
      options.push({ key, value });
    }
    return options;
  },
  serialize(model) {
    const rules = model.rules.map((rule) =>
      rule.type === "FINAL"
        ? `FINAL,${rule.policy}`
        : `${rule.type},${rule.value},${rule.policy}${rule.noResolve ? ",no-resolve" : ""}`,
    );
    return [
      "# Generated by RouteKit · Shadowrocket configuration",
      "# Select your own proxy server in Shadowrocket, then use Configuration routing.",
      "# Application presets are starter domain rules; validate routing and DNS on your device.",
      "",
      "[General]",
      "bypass-system = true",
      `dns-server = ${model.servers.join(", ")}`,
      `fallback-dns-server = ${model.servers.join(", ")}`,
      `ipv6 = ${model.ipv6}`,
      "prefer-ipv6 = false",
      "dns-direct-system = false",
      "dns-direct-fallback-proxy = false",
      "udp-policy-not-supported-behaviour = REJECT",
      ...model.general.map((option) => `${option.key} = ${option.value}`),
      "",
      "[Rule]",
      ...rules,
      ...(model.hosts.length
        ? [
            "",
            "[Host]",
            ...model.hosts.map((host) => `${host.hostname} = ${host.address}`),
          ]
        : []),
      "",
    ].join("\n");
  },
};
